/*

 DO NOT TOUCH!

Everything in this file is autogenerated. Edit on own
risk.

 */

#import "{{viewname}}.h"

@interface {{viewname}} ()

@end

@implementation {{viewname}}

- (void)viewDidLoad {
    [super viewDidLoad];


{{content}}


}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}


@end
