/*

 DO NOT TOUCH!

Everything in this file is autogenerated. Edit on own
risk. 

 */

#import <UIKit/UIKit.h>

@interface {{viewname}} : UIViewController


{{content}}

/*
@property(nonatomic, strong) UIView *view1;
@property(nonatomic, strong) UIView *view2;

@property(nonatomic, strong) UIImageView *imageView1;

 */
// @property(nonatomic, strong) UILabel *label1;
//@property (nonatomic, strong) UIButton *button1;




@end
